spring.application.name=boisgo
spring.datasource.url=jdbc:postgresql://localhost:5433/orlik_booking
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.flyway.enabled=true

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

logging.level.com.orlik.booking=DEBUG
logging.level.org.springframework.security=INFO